---
- hosts: localhost
  vars_files:
    - vars/infra.yml

  tasks:
   - name: Create project
     selvpc_projects:
       project_name: "{{ project_name }}"
     register: project_out

   - name: Set quotas on created project
     selvpc_quotas:
       project_id: "{{ project_out.project.id }}"
       quotas:
         compute_cores:
         - region: ru-2
           zone: ru-2a
           value: "{{ compute_cores }}"
         compute_ram:
         - region: ru-2
           zone: ru-2a
           value: "{{ compute_ram }}"
         volume_gigabytes_basic:
         - region: ru-2
           zone: ru-2a
           value: "{{ volume_gigabytes_basic }}"
         volume_gigabytes_universal:
         - region: ru-2
           zone: ru-2a
           value: "{{ volume_gigabytes_universal }}"
         volume_gigabytes_fast:
         - region: ru-2
           zone: ru-2a
           value: "{{ volume_gigabytes_fast }}"

     register: quotas_out

   - name: Create user
     selvpc_users:
       username: "{{ username }}"
       password: "{{ password }}"
     register: user_out

   - name: Add created user to project
     selvpc_roles:
       project_id: "{{ project_out.project.id }}"
       user_id: "{{ user_out.user.id }}"

   - name: Create public net
     selvpc_subnets:
       project_id: "{{ project_out.project.id }}"
       subnets:
        - region: ru-2
          type: ipv4
          quantity: 1
          prefix_length: 29
     register: network_out

   - name: Get info about specific subnet
     selvpc_subnets:
       subnet_id: "{{ network_out|json_query('subnets[0].id') }}"
     register: network

   - local_action: copy content="{{ network }}" dest="vars/subnet.yml"

   - name: Create key
     os_keypair:
       state: present
       auth:
         auth_url: https://api.selvpc.ru/identity/v3
         username: "{{ username }}"
         password: "{{ password }}"
         project_name: "{{ project_name }}"
       name: ansible_key
       region_name: ru-2
       public_key_file: "{{ '~' | expanduser }}/.ssh/id_rsa.pub"
     register: key

   - name: Create flavor
     os_nova_flavor:
       state: present
       auth:
         auth_url: https://api.selvpc.ru/identity/v3
         username: "{{ username }}"
         password: "{{ password }}"
         project_name: "{{ project_name }}"
       name: "tmp3_{{ item }}"
       ram: "{{ servers[item].compute_ram }}"
       vcpus: "{{ servers[item].compute_cores }}"
       disk: 0
       region_name: ru-2
       is_public: True
     with_items: "{{ servers }}"
     register: flavor


